const BUILD='2026.09.30-settlement-import1';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL');
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
const INGEST_SECRET=Deno.env.get('INGEST_SECRET');
const SHEET_IMPORT_ENABLED=Deno.env.get('SHEET_IMPORT_ENABLED')==='true';
const enc=new TextEncoder();

function clean(v){return String(v??'').trim();}
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=clean(v).replace(/[^\d.,-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replaceAll('.','').replace(',','.');else if(/^-?\d{1,3}(?:[.,]\d{3})+$/.test(s))s=s.replace(/[.,]/g,'');else s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0;}
function sameSecret(p){const a=enc.encode(p||''),b=enc.encode(INGEST_SECRET||'');if(!b.length||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0;}
function legacyDate(v){const s=clean(v);if(!s)return null;if(/^\d{4}-\d{2}-\d{2}T/.test(s))return s;let m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);if(!m)return null;const hh=String(m[4]||'00').padStart(2,'0'),mm=String(m[5]||'00').padStart(2,'0'),ss=String(m[6]||'00').padStart(2,'0');return `${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}T${hh}:${mm}:${ss}+07:00`;}
async function rest(table,q={},method='GET',body){const u=new URL(`${SUPABASE_URL}/rest/v1/${table}`);for(const[k,v]of Object.entries(q))u.searchParams.set(k,v);const r=await fetch(u,{method,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',Prefer:method==='POST'&&q.on_conflict?'return=representation,resolution=merge-duplicates':'return=representation'},...(body===undefined?{}:{body:JSON.stringify(body)})});const t=await r.text();if(!r.ok)throw new Error(`Database ${r.status}: ${t.slice(0,300)}`);return t?JSON.parse(t):[];}
function mapRow(x){const id=clean(x.id),orderId=clean(x.order_id);if(!id||!orderId)return null;let bills=[];if(Array.isArray(x.bill_urls))bills=x.bill_urls.map(clean).filter(Boolean);else{try{const a=JSON.parse(clean(x.bill_urls)||'[]');if(Array.isArray(a))bills=a.map(clean).filter(Boolean);}catch{}}
 const status=clean(x.status).toUpperCase();return {id,order_id:orderId,sale_username:clean(x.sale_username),sale_name:clean(x.sale_name),flower_total:num(x.flower_total),accessory_total:num(x.accessory_total),vat:num(x.vat),ship_fee:num(x.ship_fee),required_amount:num(x.required_amount),bill_urls:[...new Set(bills)],note:clean(x.note),status:['PENDING','APPROVED','REJECTED'].includes(status)?status:'PENDING',submitted_at:legacyDate(x.submitted_at)||new Date().toISOString(),admin_username:clean(x.admin_username)||null,admin_name:clean(x.admin_name)||null,reviewed_at:legacyDate(x.reviewed_at),rejection_reason:clean(x.rejection_reason)};}
Deno.serve(async req=>{const h={'Content-Type':'application/json; charset=utf-8'};if(req.method!=='POST')return new Response(JSON.stringify({ok:false,build:BUILD,message:'POST only'}),{status:405,headers:h});if(!SUPABASE_URL||!SERVICE_KEY||!INGEST_SECRET)return new Response(JSON.stringify({ok:false,build:BUILD,message:'Not configured'}),{status:503,headers:h});if(!sameSecret(req.headers.get('x-ingest-secret')||''))return new Response(JSON.stringify({ok:false,build:BUILD,message:'Unauthorized'}),{status:401,headers:h});if(!SHEET_IMPORT_ENABLED)return new Response(JSON.stringify({ok:false,code:'IMPORT_DISABLED',message:'Không nhập tất toán từ Sheet khi website là nguồn chính.'}),{status:409,headers:h});try{const body=await req.json();const raw=Array.isArray(body.settlements)?body.settlements:[];if(raw.length>100)throw new Error('Tối đa 100 settlement mỗi batch.');const mapped=raw.map(mapRow).filter(Boolean);const byId=new Map();for(const row of mapped)byId.set(row.id,row);const rows=[...byId.values()];if(rows.length)await rest('settlement_requests',{on_conflict:'id'},'POST',rows);const approved=[...new Set(rows.filter(x=>x.status==='APPROVED').map(x=>x.order_id))];for(const orderId of approved){await rest('orders',{id:'eq.'+orderId},'PATCH',{settled:true,updated_at:new Date().toISOString()});}
return new Response(JSON.stringify({ok:true,build:BUILD,received:raw.length,processed:rows.length,skipped:raw.length-rows.length,approvedOrders:approved.length}),{headers:h});}catch(e){console.error('Settlement ingest failed:',e);return new Response(JSON.stringify({ok:false,build:BUILD,message:'Settlement sync failed'}),{status:500,headers:h});}});