const fs=require('fs');
const assert=require('assert');
const p='supabase/functions/meehoasg-api-core/index.js';
assert.ok(fs.existsSync(p),'consolidated core must exist');
const s=fs.readFileSync(p,'utf8');
assert.ok(s.includes("const BUILD='2026.10.07-core5-full-paid'"),'core5 full-paid build marker must be current');
assert.ok(s.includes("const LEGACY_API=`${SUPABASE_URL}/functions/v1/meehoasg-api`"),'remaining compatibility fallback may only call legacy API directly');
for(const old of ['meehoasg-api-v36','meehoasg-api-v361','meehoasg-api-v362','meehoasg-api-v363','meehoasg-api-v364','meehoasg-api-v365']) assert.ok(!s.includes(`/functions/v1/${old}`),`core must not chain through ${old}`);
for(const route of ["name==='loginAndBootstrap'","name==='getCurrentUserAndBootstrap'","name==='getProductionOrders'","name==='getOrders'","name==='getDashboardSummary'","name==='getKpi'","name==='getFlowerInventory'","name==='getOrder'","name==='getDebtReview'","name==='getFullPaidReport'"]) assert.ok(s.includes(route),`${route} must be routed directly in core`);
assert.ok(s.includes('loginAndBootstrapCore'),'login bootstrap must be direct');
assert.ok(s.includes('currentBootstrapCore'),'session restore bootstrap must be direct');
assert.ok(s.includes('fastProduction'),'production initial/load route must be direct');
assert.ok(s.includes("visibilityRule:'SALE_READ_ALL_EDIT_OWN'"),'sale visibility rule must be explicit');
assert.ok(s.includes("identityRule:'APP_USERS_CANONICAL'"),'KPI must use app_users as canonical identity');
assert.ok(s.includes("if(!(r.settled||r.full_paid))continue"),'KPI revenue must use payment-check approved or Full Paid orders');
assert.ok(s.includes('cardQty(row)*10000'),'card quantity must affect accessory total');
assert.ok(s.includes('imageRetentionApplied:true'),'edit-order image deletion/retention must survive consolidation');
assert.ok(s.includes("proxy:'core5'"),'perf output must identify consolidated core5');
assert.ok(s.includes("legacyFallback:!['loginAndBootstrap','getCurrentUserAndBootstrap','getProductionOrders','getOrders','getDashboardSummary','getKpi','getFlowerInventory','getOrder','getDebtReview','getFullPaidReport','createOrder','updateOrder'].includes(name)"),'critical operational routes must not report legacy fallback');
assert.ok(s.includes('persistFormExtras'),'order form extras must persist in API core');
assert.ok(s.includes('ship_fee:num(o.shipFee)'),'ship fee selected in the order form must reach the order row');
assert.ok(s.includes('fullPaidReport'),'core must own Full Paid audit report');
assert.ok(s.includes('fullPaidInputError'),'core must enforce Full Paid evidence');
console.log('consolidated core5 contract OK');
