const fs=require('fs');
const assert=require('assert');
const p='supabase/functions/meehoasg-api-core/index.js';
assert.ok(fs.existsSync(p),'consolidated core must exist');
const s=fs.readFileSync(p,'utf8');
assert.ok(s.includes("const BUILD='2026.10.08-core6-atomic'"),'core5 full-paid build marker must be current');
assert.ok(s.includes("const LEGACY_API=`${SUPABASE_URL}/functions/v1/meehoasg-api`"),'remaining compatibility fallback may only call legacy API directly');
for(const old of ['meehoasg-api-v36','meehoasg-api-v361','meehoasg-api-v362','meehoasg-api-v363','meehoasg-api-v364','meehoasg-api-v365']) assert.ok(!s.includes(`/functions/v1/${old}`),`core must not chain through ${old}`);
for(const route of ["name==='loginAndBootstrap'","name==='getCurrentUserAndBootstrap'","name==='getProductionOrders'","name==='getOrders'","name==='getDashboardSummary'","name==='getKpi'","name==='getFlowerInventory'","name==='getOrder'","name==='getDebtReview'","name==='getFullPaidReport'"]) assert.ok(s.includes(route),`${route} must be routed directly in core`);
assert.ok(s.includes('loginAndBootstrapCore'),'login bootstrap must be direct');
assert.ok(s.includes('currentBootstrapCore'),'session restore bootstrap must be direct');
assert.ok(s.includes('fastProduction'),'production initial/load route must be direct');
assert.ok(s.includes("visibilityRule:'SALE_READ_ALL_EDIT_OWN'"),'sale visibility rule must be explicit');
assert.ok(s.includes("identityRule:'APP_USERS_CANONICAL'"),'KPI must use app_users as canonical identity');
assert.ok(s.includes("if(!(r.settled||r.full_paid))continue"),'KPI revenue must use payment-check approved or Full Paid orders');
assert.ok(s.includes('cardQty(row)*10000'),'card quantity must affect accessory total');
assert.ok(s.includes('createOperationService'),'core must use the canonical transaction service');
assert.ok(s.includes("proxy:'core6'"),'perf identifies atomic runtime');
assert.ok(s.includes('mutationRoutes.has(name)'),'operational writes route directly without legacy fallback');
assert.ok(!s.includes('persistFormExtras'),'no independent post-save patches');
assert.ok(!s.includes('persistCardQty'),'card quantity must commit with the order');
const ops=fs.readFileSync('supabase/functions/_shared/operations.js','utf8');
assert.ok(ops.includes('mee_ops_mutate'),'one mutation RPC');
assert.ok(ops.includes('ship_fee:shipActive?operationMoney(d.shipFee):0'),'form ship fee is normalized');
assert.ok(s.includes('fullPaidReport'),'core must own Full Paid audit report');
assert.ok(ops.includes('FULL_PAID_EVIDENCE_REQUIRED'),'shared service enforces Full Paid evidence');
console.log('consolidated core5 contract OK');
