const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function harness(name,enabled=false,rows=[]){let handler,calls=[];const context={URL,TextEncoder,Request,Response,Date,console,crypto:webcrypto,Deno:{env:{get:k=>({SUPABASE_URL:'https://test.local',SUPABASE_SERVICE_ROLE_KEY:'test-only',INGEST_SECRET:'test-only',SHEET_IMPORT_ENABLED:enabled?'true':undefined})[k]},serve:fn=>handler=fn},fetch:async(url,args)=>{calls.push({url:String(url),...args});return new Response(JSON.stringify(rows),{status:200});}};vm.createContext(context);vm.runInContext(fs.readFileSync('supabase/functions/'+name+'/index.js','utf8'),context);return {calls,request:body=>handler(new Request('https://test.local',{method:'POST',headers:{'x-ingest-secret':'test-only','content-type':'application/json'},body:JSON.stringify(body)}))};}
test('production order and settlement import routes are blocked by default before any DB write',async()=>{
 for(const [name,body] of [['meehoasg-ingest',{orders:[{id:'ONE'}]}],['meehoasg-settlement-ingest',{settlements:[{id:'SET',order_id:'ONE',status:'APPROVED'}]}]]){const h=harness(name),r=await h.request(body);assert.equal(r.status,409);assert.equal((await r.json()).code,'IMPORT_DISABLED');assert.equal(h.calls.length,0);}
});
test('position writeback remains allowed and never changes money, note or order status',async()=>{
 const h=harness('meehoasg-ingest'),r=await h.request({action:'recordSheetPositions',updates:[{id:'ONE',source_sheet:'Tháng 10/2026',source_row:3,note:'EVIL',flower_total:1,settled:true}]});assert.equal(r.status,200);assert.equal(h.calls.length,1);const patch=JSON.parse(h.calls[0].body);assert.equal(patch.source_sheet,'Tháng 10/2026');assert.equal(patch.source_row,3);assert.equal(patch.needs_sheet_sync,false);assert.ok(patch.sheet_synced_at);for(const field of ['flower_total','note','settled'])assert.equal(field in patch,false);
});
test('writeback feed carries card quantity and complete Full Paid evidence',async()=>{const h=harness('meehoasg-writeback-feed');assert.equal((await h.request({})).status,200);const select=new URL(h.calls[0].url).searchParams.get('select').split(',');for(const field of ['card_qty','full_paid','full_paid_total','full_paid_bill_urls','full_paid_by','full_paid_at','full_paid_invalidated_at','full_paid_invalidated_reason'])assert.ok(select.includes(field),field);});

test('versioned stale Sheet ACK reports conflict and uses atomic version predicate',async()=>{const h=harness('meehoasg-ingest');const r=await h.request({action:'recordSheetPositions',updates:[{id:'ONE',expectedUpdatedAt:'2026-10-09T01:00:00Z',source_row:3}]});assert.equal((await r.json()).conflicts,1);assert.equal(new URL(h.calls[0].url).searchParams.get('updated_at'),'eq.2026-10-09T01:00:00Z');});

test('successful Sheet ACK confirms the matched row and bounds batches',async()=>{const h=harness('meehoasg-ingest',false,[{id:'ONE'}]);let r=await h.request({action:'recordSheetPositions',updates:[{id:'ONE',source_sheet:'Sheet',source_row:3,expectedUpdatedAt:'2026-10-09T01:00:00Z'}]});const result=await r.json();assert.equal(result.ok,true);assert.equal(result.updated,1);assert.equal(result.conflicts,0);r=await h.request({action:'recordSheetPositions',updates:Array.from({length:201},()=>({id:'ONE'}))});assert.equal(r.status,500);assert.equal(h.calls.length,1);});
