const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const user={username:'sale1',role:'SALE'},order={customer:'Test',date:'2026-10-08',time:'10:00',flower:'Hoa',flowerTotal:500000,shipping:'Ghé lấy',imageFiles:[{data:'sample'}],fullPaidBillFiles:[{data:'bill'}]};
async function service(options={}){const {createOperationService}=await import('../supabase/functions/_shared/operations.js');let calls=[],deletions=[];const svc=createOperationService({one:async()=>null,sha256:async s=>hash(s),newId:()=> 'ONE',uploadImages:async(files,bucket)=>{calls.push(bucket);if(options.uploadFail&&bucket==='settlement-bills')throw Error('UPLOAD_FAIL');return files.map((f,i)=>`supabase://${bucket}/${i}.jpg`);},discardImages:async urls=>deletions.push(...urls),db:async(name)=>{if(name==='rpc/mee_ops_lookup')return null;if(options.unknown)throw Error('LOST_RESPONSE');return options.result||{ok:false,code:'TEST_REJECTED'};}});return {svc,calls,deletions};}
test('SQL rejection removes uploaded evidence without committing an order',async()=>{const h=await service();await h.svc.run('createOrder',{requestId:'key',order},user);assert.deepEqual(h.deletions,['supabase://order-images/0.jpg','supabase://settlement-bills/0.jpg']);});
test('failed bill batch also cleans the already uploaded sample batch',async()=>{const h=await service({uploadFail:true});await assert.rejects(()=>h.svc.run('createOrder',{requestId:'key',order},user),/UPLOAD_FAIL/);assert.deepEqual(h.deletions,['supabase://order-images/0.jpg']);});
test('unknown SQL response retains evidence for committed receipt recovery',async()=>{const h=await service({unknown:true});await assert.rejects(()=>h.svc.run('createOrder',{requestId:'key',order},user),/LOST_RESPONSE/);assert.deepEqual(h.deletions,[]);});
test('concurrent duplicate receipt cleans only this losing request uploads',async()=>{const h=await service({result:{ok:true,idempotent:true,row:{image_urls:['supabase://order-images/winner.jpg'],full_paid_bill_urls:['supabase://settlement-bills/winner.jpg']}}});await h.svc.run('createOrder',{requestId:'key',order},user);assert.equal(h.deletions.length,2);assert.ok(h.deletions.every(u=>!u.includes('winner')));});
test('storage batch validates all files before uploading, compensates an ambiguous upload',async()=>{
 const {createOperationStorage}=await import('../supabase/functions/_shared/storage.js');let requests=[],n=0;
 const storage=createOperationStorage({url:'https://test',key:'test',uuid:()=>String(++n),log(){},fetcher:async(url,args)=>{requests.push({url,...args});if(args.method==='POST')throw Error('UPLOAD_LOST_RESPONSE');return {ok:true};}});
 await assert.rejects(()=>storage.uploadImages([{data:'data:image/png;base64,YQ=='},{data:'bad'}],'order-images'),/không hợp lệ/);assert.equal(requests.length,0);
 await assert.rejects(()=>storage.uploadImages([{data:'data:image/png;base64,YQ=='}],'order-images'),/UPLOAD_LOST_RESPONSE/);assert.deepEqual(requests.map(r=>r.method),['POST','DELETE']);assert.deepEqual(JSON.parse(requests[1].body).prefixes,['2.png']);
});
