import {createOperationStorage} from '../_shared/storage.js';
import {createOperationService} from '../_shared/operations.js';
const BUILD='2026.10.08-core6-atomic';
const UI_BUILD='2026.09.28-supabase-v3';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL');
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')||'';
const GEMINI_KEY=Deno.env.get('GEMINI_API_KEY')||'';
const ENV_GEMINI_MODEL=Deno.env.get('GEMINI_MODEL')||'';
const PASSWORD_SALT=Deno.env.get('LEGACY_PASSWORD_SALT')||'MEE-FLOWER-V4';
const SESSION_MS=30*24*60*60*1000;
const LEGACY_API=`${SUPABASE_URL}/functions/v1/meehoasg-api`;
const ALLOWED=['https://ops.meehoasg.com','http://ops.meehoasg.com','https://meehoasg.com','http://meehoasg.com'];

function clean(v){return String(v??'').trim()}
function num(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let raw=String(v??'0').replace(/[^\d.,-]/g,'');if(raw.includes(',')&&raw.includes('.'))raw=raw.replaceAll('.','').replace(',','.');else if(/^-?\d{1,3}(?:[.,]\d{3})+$/.test(raw))raw=raw.replace(/[.,]/g,'');else raw=raw.replace(',','.');const n=Number(raw);return Number.isFinite(n)?n:0}
function norm(v){return clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase().replace(/\s+/g,' ')}
function saleKey(v){return norm(v).replace(/[^a-z0-9]/g,'')}
function dateToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function cleanTime(v){const m=clean(v).match(/(\d{1,2}):(\d{2})/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:clean(v).slice(0,5)}
function fail(message,code){return {ok:false,message,...(code?{code}:{})}}
async function sha256(text){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));return [...bytes].map(n=>n.toString(16).padStart(2,'0')).join('')}
function same(a,b){a=String(a);b=String(b);if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function sessionToken(){return [...crypto.getRandomValues(new Uint8Array(32))].map(n=>n.toString(16).padStart(2,'0')).join('')}
function usernameNorm(v){return norm(v).replace(/\s+/g,'')}
function publicUser(user){return {username:user.username,name:user.display_name,role:user.role,active:user.active}}

async function db(table,query={},method='GET',body){
  const url=new URL(`${SUPABASE_URL}/rest/v1/${table}`);
  Object.entries(query).forEach(([k,v])=>{if(v!==undefined&&v!==null)url.searchParams.set(k,String(v))});
  const res=await fetch(url,{method,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',Prefer:method==='GET'?'count=exact':(query.on_conflict?'return=representation,resolution=merge-duplicates':'return=representation')},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const text=await res.text();if(!res.ok)throw new Error(`DB ${res.status}: ${text.slice(0,260)}`);return text?JSON.parse(text):[];
}
async function all(table,query={}){const out=[];for(let offset=0;;offset+=1000){const part=await db(table,{...query,limit:'1000',offset:String(offset)});out.push(...part);if(part.length<1000)return out}}
async function one(table,query={}){return (await db(table,{...query,limit:'1'}))[0]||null}
async function requireUser(payload,roles){const raw=clean(payload?.token);if(!raw||!/^[0-9a-f]{64}$/i.test(raw))throw new Error('Phiên đăng nhập không hợp lệ hoặc đã hết hạn.');const session=await one('app_sessions',{token_hash:`eq.${await sha256(raw)}`,select:'username,expires_at'});if(!session||Date.parse(session.expires_at)<=Date.now())throw new Error('Phiên đăng nhập không hợp lệ hoặc đã hết hạn.');const user=await one('app_users',{username:`eq.${session.username}`,select:'username,display_name,role,active'});if(!user||!user.active)throw new Error('Tài khoản đã bị khóa.');if(roles&&!roles.includes(user.role))throw new Error('Không có quyền thực hiện.');return user}
async function loginCore(payload){const username=usernameNorm(payload?.username),password=String(payload?.password||'');if(!username||!password)return fail('Sai tài khoản hoặc mật khẩu.');const attempt=await one('login_attempts',{username:`eq.${username}`});if(attempt?.blocked_until&&Date.parse(attempt.blocked_until)>Date.now())return fail('Đăng nhập quá nhiều lần. Vui lòng thử lại sau.');const user=await one('app_users',{username:`eq.${username}`,select:'username,display_name,role,active,password_hash'});const expected=await sha256(PASSWORD_SALT+'|'+password),valid=user&&user.active&&same(user.password_hash,expected);if(!valid){const count=(attempt?.attempts||0)+1;await db('login_attempts',{on_conflict:'username'},'POST',{username,attempts:count,blocked_until:count>=5?new Date(Date.now()+15*60*1000).toISOString():null,updated_at:new Date().toISOString()});return fail('Sai tài khoản hoặc mật khẩu.')}if(attempt)await db('login_attempts',{username:`eq.${username}`},'DELETE');const raw=sessionToken();await db('app_sessions',{},'POST',{token_hash:await sha256(raw),username,expires_at:new Date(Date.now()+SESSION_MS).toISOString()});return {ok:true,token:raw,user:publicUser(user)}}

async function delegate(request,input){const h={'Content-Type':'application/json'};const auth=request.headers.get('authorization');const api=request.headers.get('apikey');if(auth)h.Authorization=auth;if(api)h.apikey=api;else if(ANON_KEY)h.apikey=ANON_KEY;const r=await fetch(LEGACY_API,{method:'POST',headers:h,body:JSON.stringify(input)});const t=await r.text();let data;try{data=t?JSON.parse(t):{}}catch{data=fail('Máy chủ trả dữ liệu không hợp lệ.','BAD_UPSTREAM')}return {status:r.status,data}}

async function saleDirectory(){const users=await all('app_users',{select:'username,display_name,role,active'});const map=new Map();for(const u of users){map.set(saleKey(u.username),u);map.set(saleKey(u.display_name),u)}return {users,map}}
function canonicalSale(raw,dir){const u=dir.map.get(saleKey(raw));return u?{username:u.username,displayName:u.display_name,known:true}:{username:'',displayName:clean(raw)||'Chưa gán',known:false}}

function cardQty(row){if(!row?.card)return 0;return Math.max(1,Math.min(99,Math.floor(num(row.card_qty)||1)))}
function accessoryTotal(row){return cardQty(row)*10000+(row.banner?35000:0)+num(row.charm_fee)+num(row.paper_fee)}
function orderTotal(row){const ship=norm(row?.shipping).includes('shop')&&row?.ship_confirmed?num(row.ship_fee):0;return num(row?.flower_total)+accessoryTotal(row)+num(row?.vat)+ship}
function paidAmount(payment,base,settled){if(settled>0)return settled;const text=norm(payment);if(!text||/chua/.test(text))return 0;if(/full|da tt|da thanh toan (?:du|toan bo)|thanh toan du/.test(text))return base;const m=text.replace(/\s/g,'').match(/([0-9.,]+)(k|tr|trieu)?/);if(!m)return /da thanh toan/.test(text)?base:0;let a=num(m[1]);if(m[2]==='tr'||m[2]==='trieu')a*=1000000;else if(m[2]==='k'||(a>0&&a<=1000&&!/\d\s*(?:đ|d|vn[dđ])(?:$|[\s),.])/i.test(text)))a*=1000;return Math.max(0,a)}
function contactFields(row){const contact=clean(row.address);const p=contact.match(/(?:SĐT|SDT)\s*:\s*([^\n]+)/i);return {phone:clean(row.phone)||(p?clean(p[1]):''),address:contact.replace(/(?:SĐT|SDT)\s*:\s*[^\n]+\n?/i,'').replace(/^Địa chỉ\s*:\s*/i,'').trim()}}
async function displayUrls(urls){const out=[];for(const url of urls||[]){const m=String(url).match(/^supabase:\/\/(order-images|settlement-bills)\/(.+)$/);if(!m){out.push(url);continue}const r=await fetch(`${SUPABASE_URL}/storage/v1/object/sign/${m[1]}/${m[2]}`,{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});if(!r.ok)continue;const s=await r.json();out.push(`${SUPABASE_URL}/storage/v1${s.signedURL}`)}return out}
const operationStorage=createOperationStorage({url:SUPABASE_URL,key:SERVICE_KEY});
const uploadEvidenceImages=operationStorage.uploadImages;
async function settlementMap(ids){if(!ids.length)return {};const unique=[...new Set(ids)],parts=[];for(let i=0;i<unique.length;i+=30){const chunk=unique.slice(i,i+30);parts.push(all('settlement_requests',{order_id:'in.('+chunk.map(id=>'"'+String(id).replaceAll('"','')+'"').join(',')+')',order:'submitted_at.desc'}))}const rows=(await Promise.all(parts)).flat(),map={};for(const row of rows)if(!map[row.order_id])map[row.order_id]=row;return map}
function decorate(row,user,settlement,dir){const contact=contactFields(row),acc=accessoryTotal(row),ship=norm(row.shipping).includes('shop')&&row.ship_confirmed?num(row.ship_fee):0,base=num(row.flower_total)+acc+num(row.vat),total=base+ship,fullPaid=!!row.full_paid,verified=!!row.settled||fullPaid,paid=fullPaid?(num(row.full_paid_total)||total):paidAmount(row.payment,base,row.settled?total:0),ss=fullPaid?'AUTO_FULL_PAID':(settlement?.status||'NONE'),locked=!!row.settled||['PENDING','APPROVED'].includes(ss),canon=canonicalSale(row.sale,dir),owner=canon.known&&saleKey(canon.username)===saleKey(user.username),canEdit=!locked&&(user.role!=='SALE'||owner);return {id:row.id,updatedAt:row.updated_at,sourceSheet:row.source_sheet||'',sourceRow:row.source_row||0,customer:row.customer,phone:contact.phone,date:row.order_date,time:cleanTime(row.order_time),flower:row.flower,imageUrls:row.image_urls||[],driveUrls:row.image_urls||[],note:row.note,shipping:row.shipping,address:contact.address,flowerTotal:num(row.flower_total),payment:row.payment,paid,sale:canon.displayName,saleUsername:canon.username,settled:!!row.settled,fullPaid,fullPaidTotal:num(row.full_paid_total),fullPaidBillUrls:row.full_paid_bill_urls||[],fullPaidBy:clean(row.full_paid_by),fullPaidAt:row.full_paid_at||null,fullPaidInvalidatedAt:row.full_paid_invalidated_at||null,fullPaidInvalidatedReason:clean(row.full_paid_invalidated_reason),paymentVerified:verified,verificationMode:fullPaid?'FULL_PAID_AUTO':(row.settled?'PAYMENT_CHECK':''),status:row.status,shipFee:num(row.ship_fee),shipConfirmed:!!row.ship_confirmed,shipFeePending:norm(row.shipping).includes('shop')&&!row.ship_confirmed,card:!!row.card,cardQty:cardQty(row),cardFee:cardQty(row)*10000,cardText:row.card_text,banner:!!row.banner,bannerText:row.banner_text,charmFee:num(row.charm_fee),charmText:row.charm_text,paperFee:num(row.paper_fee),paperText:row.paper_text,vat:num(row.vat),accessoryTotal:acc,totalDue:total,debt:verified?0:Math.max(0,total-paid),hasAccessories:acc>0,settlementStatus:ss,settlementRequestId:settlement?.id||'',settlementReason:settlement?.rejection_reason||'',locked,canEdit,canShip:!locked,canOperate:!locked&&['ADMIN','THO_OPS'].includes(user.role),canSubmitSettlement:!locked&&!fullPaid&&row.status==='Đã giao'&&(user.role==='ADMIN'||owner),detailLoaded:true}}


const operations=createOperationService({db,one,uploadImages:uploadEvidenceImages,discardImages:operationStorage.discard,sha256,newId:prefix=>prefix+'-'+crypto.randomUUID().replaceAll('-','').slice(0,16).toUpperCase()});
async function operationResult(action,payload,user){
  const result=await operations.run(action,payload,user);
  if(!result?.ok)return result;
  const output={...result};delete output.row;
  const row=await one('orders',{id:`eq.${result.orderId}`})||result.row;
  if(row){const dir=await saleDirectory();output.order=await decoratedExisting(row,user,dir);}
  return output;
}
async function decoratedExisting(row,user,dir){
  const [sm,images,bills]=await Promise.all([settlementMap([row.id]),displayUrls(row.image_urls||[]),displayUrls(row.full_paid_bill_urls||[])]);
  return decorate({...row,image_urls:images,full_paid_bill_urls:bills},user,sm[row.id],dir);
}
async function fastOrder(payload){const user=await requireUser(payload),id=clean(payload.orderId),row=await one('orders',{id:`eq.${id}`});if(!row)return fail('Không tìm thấy đơn.');const dir=await saleDirectory(),sm=await settlementMap([id]),shown=decorate({...row,image_urls:await displayUrls(row.image_urls||[])},user,sm[id],dir);shown.fullPaidBillUrls=await displayUrls(row.full_paid_bill_urls||[]);return {ok:true,order:shown}}
async function fastDebt(payload){const user=await requireUser(payload),dir=await saleDirectory(),start=clean(payload.start)||dateToday(),end=clean(payload.end)||start,sale=user.role==='ADMIN'?norm(payload.sale):null,rows=await all('orders',{and:`(order_date.gte.${start},order_date.lte.${end})`,order:'order_date.asc,order_time.asc'}),sm=await settlementMap(rows.map(r=>r.id)),decorated=await Promise.all(rows.map(async r=>decorate({...r,image_urls:await displayUrls(r.image_urls||[])},user,sm[r.id],dir))),items=decorated.filter(o=>{if(o.status!=='Đã giao'||o.paymentVerified||o.debt<=0)return false;if(user.role==='ADMIN')return !sale||norm(o.sale)===sale;return saleKey(o.saleUsername||o.sale)===saleKey(user.username)});return {ok:true,range:{start,end},items,summary:{orders:items.length,debt:items.reduce((n,o)=>n+o.debt,0),shipFeePending:items.filter(o=>o.shipFeePending).length},scope:user.role==='ADMIN'?'ADMIN':'SELF',fullPaidExcluded:true}}
async function fullPaidReport(payload){const user=await requireUser(payload,['ADMIN']),month=clean(payload.month)||dateToday().slice(0,7);if(!/^\d{4}-\d{2}$/.test(month))return fail('Tháng báo cáo không hợp lệ.');const start=month+'-01',end=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).toISOString().slice(0,10),dir=await saleDirectory(),rows=await all('orders',{and:`(order_date.gte.${start},order_date.lte.${end})`,order:'order_date.asc,order_time.asc'}),auditRows=rows.filter(r=>r.full_paid||r.full_paid_invalidated_at),items=[];for(let i=0;i<auditRows.length;i+=20){const batch=await Promise.all(auditRows.slice(i,i+20).map(async row=>{const canon=canonicalSale(row.sale,dir),total=orderTotal(row),[bills,samples]=await Promise.all([displayUrls(row.full_paid_bill_urls||[]),displayUrls(row.image_urls||[])]),active=!!row.full_paid,exception=!bills.length||!samples.length||(!active&&!!row.full_paid_invalidated_at)||total>num(row.full_paid_total);return {id:row.id,customer:row.customer,date:row.order_date,time:cleanTime(row.order_time),sale:canon.displayName,saleUsername:canon.username,flower:row.flower,flowerTotal:num(row.flower_total),accessoryTotal:accessoryTotal(row),vat:num(row.vat),shipFee:norm(row.shipping).includes('shop')&&row.ship_confirmed?num(row.ship_fee):0,totalDue:total,paidTotal:num(row.full_paid_total),status:active?'FULL_PAID':'INVALIDATED',fullPaidAt:row.full_paid_at,invalidatedAt:row.full_paid_invalidated_at,invalidatedReason:clean(row.full_paid_invalidated_reason),billUrls:bills,imageUrls:samples,exception}}));items.push(...batch)}return {ok:true,month,items,summary:{orders:items.length,active:items.filter(x=>x.status==='FULL_PAID').length,exceptions:items.filter(x=>x.exception).length,flowerRevenue:items.filter(x=>x.status==='FULL_PAID').reduce((n,x)=>n+x.flowerTotal,0),collected:items.filter(x=>x.status==='FULL_PAID').reduce((n,x)=>n+x.paidTotal,0)},auditRule:'FULL_PAID_WITH_EVIDENCE'}}

async function fastProduction(payload){const user=await requireUser(payload),dir=await saleDirectory(),date=clean(payload.date)||dateToday(),rows=await all('orders',{and:`(order_date.gte.${date},order_date.lte.${date})`,order:'order_time.asc'}),sm=await settlementMap(rows.map(r=>r.id));const orders=await Promise.all(rows.map(async r=>decorate({...r,image_urls:await displayUrls(r.image_urls||[])},user,sm[r.id],dir)));return {ok:true,date,orders,visibilityRule:'SALE_READ_ALL_EDIT_OWN'}}

async function fastOrders(payload){
  const user=await requireUser(payload),dir=await saleDirectory();
  const start=clean(payload.start)||dateToday(),end=clean(payload.end)||start,q=norm(payload.q);
  const page=Math.max(1,Math.floor(num(payload.page)||1)),pageSize=Math.min(200,Math.max(20,Math.floor(num(payload.pageSize)||80)));
  // A submitted search spans every order date. Date filters still apply when the search is cleared.
  // Filter BEFORE signing thumbnail URLs or reading settlement details to avoid expensive work on every historical order.
  const rows=await all('orders',q?{
    order:'order_date.desc,order_time.desc'
  }:{
    and:`(order_date.gte.${start},order_date.lte.${end})`,
    order:'order_date.asc,order_time.asc'
  });
  const matched=q?rows.filter(r=>norm([r.customer,r.phone,r.id,r.flower,r.sale].join(' ')).includes(q)):rows;
  const selected=matched.slice((page-1)*pageSize,page*pageSize);
  const sm=await settlementMap(selected.map(r=>r.id));
  const items=await Promise.all(selected.map(async r=>decorate({...r,image_urls:await displayUrls(r.image_urls||[])},user,sm[r.id],dir)));
  return {
    ok:true,range:q?null:{start,end},searchScope:q?'ALL_DATES':'SELECTED_DATE',
    page,pageSize,total:matched.length,items,hasMore:page*pageSize<matched.length,
    visibilityRule:'SALE_READ_ALL_EDIT_OWN'
  };
}

async function fastDashboard(payload){const user=await requireUser(payload),dir=await saleDirectory(),start=clean(payload.start)||dateToday(),end=clean(payload.end)||start;const rows=await all('orders',{select:'id,updated_at,customer,phone,order_date,order_time,flower,note,shipping,address,flower_total,payment,sale,status,settled,full_paid,full_paid_total,full_paid_bill_urls,full_paid_by,full_paid_at,full_paid_invalidated_at,full_paid_invalidated_reason,ship_fee,ship_confirmed,card,card_qty,banner,charm_fee,paper_fee,vat,image_urls',and:`(order_date.gte.${start},order_date.lte.${end})`,order:'order_date.asc,order_time.asc'});const sm=await settlementMap(rows.map(r=>r.id));const orders=rows.map(r=>decorate(r,user,sm[r.id],dir));const summary={orders:0,revenue:0,grossRevenue:0,settledRevenue:0,unsettledRevenue:0,debt:0,cms:0,'Chờ bó':0,'Đã bó':0,'Đã giao':0,unsettled:0,alerts:0};const daily=new Map(),nearUnpacked=[],packedOverdue=[];const now=Date.now();for(const o of orders){summary.orders++;summary.grossRevenue+=o.flowerTotal;summary.debt+=o.debt;summary[o.status]=(summary[o.status]||0)+1;if(o.paymentVerified)summary.settledRevenue+=o.flowerTotal;else{summary.unsettledRevenue+=o.flowerTotal;summary.unsettled++}const who=o.saleUsername||saleKey(o.sale)||o.sale,key=`${o.date}|${who}`,x=daily.get(key)||{date:o.date,sale:o.sale,saleUsername:o.saleUsername||'',orders:0,settledOrders:0,unsettledOrders:0,grossRevenue:0,settledRevenue:0,unsettledRevenue:0,revenue:0};x.orders++;x.grossRevenue+=o.flowerTotal;if(o.paymentVerified){x.settledOrders++;x.settledRevenue+=o.flowerTotal}else{x.unsettledOrders++;x.unsettledRevenue+=o.flowerTotal}x.revenue=x.settledRevenue;daily.set(key,x);const due=Date.parse(`${o.date}T${o.time||'00:00'}:00+07:00`);if(Number.isFinite(due)){if(o.status==='Chờ bó'&&due>=now&&due-now<=3600000)nearUnpacked.push(o);if(o.status==='Đã bó'&&due<now)packedOverdue.push(o)}}summary.revenue=summary.grossRevenue;summary.cms=summary.settledRevenue*.08;summary.nearUnpacked=nearUnpacked.length;summary.packedOverdue=packedOverdue.length;summary.alerts=summary.nearUnpacked+summary.packedOverdue;const salesDaily=[...daily.values()].sort((a,b)=>a.date.localeCompare(b.date)||(b.grossRevenue-a.grossRevenue)||a.sale.localeCompare(b.sale,'vi'));return {ok:true,range:{start,end},summary,attentionGroups:{nearUnpacked:nearUnpacked.slice(0,20),packedOverdue:packedOverdue.slice(0,20)},attention:[...nearUnpacked,...packedOverdue].slice(0,40),salesDaily,revenueRule:'PAYMENT_VERIFIED',revenueLabels:{unsettled:'Doanh thu chưa xác nhận',settled:'Doanh thu đã xác nhận / Full Paid'},visibilityRule:'SALE_READ_ALL_EDIT_OWN'}}

async function fastKpi(payload){const user=await requireUser(payload),month=clean(payload.month)||dateToday().slice(0,7);if(!/^\d{4}-\d{2}$/.test(month))return fail('Tháng KPI không hợp lệ.');const start=month+'-01',end=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).toISOString().slice(0,10),dir=await saleDirectory();const rows=await all('orders',{select:'sale,flower_total,settled,full_paid',and:`(order_date.gte.${start},order_date.lte.${end})`}),penalties=await all('kpi_operations',{month:'eq.'+month}),grouped={};for(const r of rows){if(!(r.settled||r.full_paid))continue;const canon=canonicalSale(r.sale,dir);if(user.role==='SALE'&&saleKey(canon.username)!==saleKey(user.username))continue;if(user.role!=='ADMIN'&&user.role!=='SALE'&&canon.username==='cmui')continue;const key=canon.username||`legacy:${saleKey(canon.displayName)}`,item=grouped[key]||{sale:canon.displayName,username:canon.username,revenue:0,orders:0,bigOrders:0};item.revenue+=num(r.flower_total);item.orders++;if(num(r.flower_total)>=500000)item.bigOrders++;grouped[key]=item}const holiday=[2,3,10,11].includes(Number(month.slice(5,7))),target=holiday?50000000:38000000,bigTarget=holiday?20:16;for(const item of Object.values(grouped)){const penalty=penalties.filter(x=>{const c1=canonicalSale(x.sale_username||x.sale_name,dir);return item.username?c1.username===item.username:saleKey(c1.displayName)===saleKey(item.sale)}).reduce((n,x)=>n+num(x.total_points),0);item.operationsScore=Math.max(0,100-penalty);item.level1=holiday?item.revenue>=target:item.revenue>target;item.bigTarget=bigTarget;item.level2=item.level1&&item.bigOrders>=bigTarget&&item.operationsScore>80;item.rate=item.level2?.10:.08;item.commission=item.revenue*item.rate;item.bonus=item.level1?300000:0}return {ok:true,month,holiday,items:Object.values(grouped),note:'Mức 2 = đạt Mức 1 + target đơn ≥500.000đ + KPI vận hành >80.',identityRule:'APP_USERS_CANONICAL',revenueRule:'PAYMENT_VERIFIED_OR_FULL_PAID'}}

function flowerKey(v){return norm(v)}
function canonicalIngredientName(value){const raw=clean(value).replace(/\s+/g,' '),n=norm(raw);if(!n)return'';if(/hong\s*(ecu|ecuador)|ecuador\s*rose|rose\s*ecuador/.test(n))return'Hồng Ecuador';if(/chiet\s*xa/.test(n))return'Chiết xạ';if(/\b(ly|li|lily|lilies)\b/.test(n)){if(/son\s*xanh/.test(n))return/dam/.test(n)?'Ly sơn xanh đậm':'Ly sơn xanh';if(/xanh/.test(n)&&/nhuom/.test(n))return/dam/.test(n)?'Ly xanh nhuộm đậm':'Ly xanh nhuộm';if(/tim\s*pastel/.test(n))return'Ly tím pastel';if(/xanh\s*mint/.test(n))return'Ly xanh mint';if(/hong/.test(n))return'Ly hồng';if(/vang\s*cam/.test(n))return'Ly vàng cam';if(/kep/.test(n))return'Ly kép';return'Ly'}return raw.charAt(0).toUpperCase()+raw.slice(1)}
function canonicalIngredients(values){const m=new Map();for(const v of Array.isArray(values)?values:[]){const n=canonicalIngredientName(v);if(n)m.set(flowerKey(n),n)}return[...m.values()]}
function aiModels(){return[...new Set(['gemini-3.8-flash',ENV_GEMINI_MODEL,'gemini-3.5-flash-lite','gemini-2.5-flash-lite','gemini-2.5-flash'].filter(Boolean))]}
async function classifyIngredients(items){const models=aiModels();if(!items.length)return{ok:true,model:null,results:[],modelsTried:[]};if(!GEMINI_KEY)return{ok:false,code:'AI_KEY_MISSING',message:'AI chưa được cấu hình API key.',modelsTried:models};const prompt=`Bạn là AI phân tích NGUYÊN LIỆU HOA cho tiệm hoa. Mỗi input là mô tả một đơn hàng. Sửa lỗi chính tả/tên đồng nghĩa nhưng giữ giống, màu, xử lý, biến thể. lily/lilies/ly/li => Ly nếu không có đặc tính. Có đặc tính thì giữ: Ly kép, Ly hồng, Ly tím pastel, Ly xanh mint, Ly xanh nhuộm, Ly sơn xanh. Hồng ecu/ecuador => Hồng Ecuador. Một đơn có nhiều loại hoa: trả tất cả. Không đếm cành, bỏ phụ kiện/bao bì. Nếu không rõ thì flowers=[] và needs_review=true. Giữ fingerprint. Chỉ trả JSON {"results":[{"fingerprint":"...","flowers":["..."],"needs_review":false}]}. DỮ LIỆU: ${JSON.stringify(items)}`;const body={contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.05,responseMimeType:'application/json'}};for(const model of models){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':GEMINI_KEY},body:JSON.stringify(body)});if(!r.ok)continue;const data=await r.json(),raw=(data?.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join(''),parsed=JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0]||'{}');if(Array.isArray(parsed.results))return{ok:true,model,results:parsed.results,modelsTried:[model]}}catch{}}return{ok:false,code:'AI_MODELS_FAILED',message:'AI nguyên liệu đang tạm thời không phản hồi.',modelsTried:models}}
function localFlowers(text){const n=norm(text),out=[];const add=x=>{if(x&&!out.includes(x))out.push(x)};const ly=clean(text).match(/(?:^|[\s,+;/])(?:ly|li|lily|lilies)\b(?:\s+(?:sơn|nhuộm|xanh|hồng|vàng|cam|kép|tím|pastel|mint|đậm))*/ig);for(const part of ly||[])add(canonicalIngredientName(part.trim()));if(/hong\s*(ecu|ecuador)|ecuador/.test(n))add('Hồng Ecuador');if(/chiet\s*xa/.test(n))add('Chiết xạ');if(/\bohara\b/.test(n))add('Hồng Ohara');if(/\b(phang|phan|carnation)\b/.test(n))add('Hoa phăng');if(/\btulip\b/.test(n))add('Tulip');if(/\bbaby\b/.test(n))add(/xanh/.test(n)?'Baby xanh':'Baby');if(/cam\s*tu\s*cau/.test(n))add('Cẩm tú cầu');if(/thanh\s*lieu/.test(n))add('Thanh liễu');if(/huong\s*duong/.test(n))add('Hướng dương');if(/mao\s*luong/.test(n))add('Mao lương');if(/dong\s*tien/.test(n))add('Đồng tiền');return out}
async function flowerInventory(payload){const user=await requireUser(payload,['ADMIN','THO_OPS']),date=clean(payload.date)||dateToday(),orders=await all('orders',{select:'id,customer,order_date,order_time,flower',and:`(order_date.gte.${date},order_date.lte.${date})`,order:'order_time.asc'});if(!orders.length)return{ok:true,status:'empty',totalOrders:0,analyzedOrders:0,reviewCount:0,items:[],reviewOrders:[],aiModel:null};const unique=new Map();for(const o of orders){const key=flowerKey(o.flower);if(key&&!unique.has(key))unique.set(key,clean(o.flower).slice(0,700))}const keyed=await Promise.all([...unique].map(async([key,content])=>({key,content,fingerprint:await sha256(`core6|${key}`)}))),cacheRows=await all('flower_cache',{select:'fingerprint,content,flowers,needs_review,updated_at',order:'updated_at.desc'}),cache=new Map(cacheRows.map(r=>[r.fingerprint,r])),pending=keyed.filter(x=>payload.forceRefresh||!cache.has(x.fingerprint));let aiModel=null,aiStatus='CACHE';for(let i=0;i<pending.length;i+=35){const batch=pending.slice(i,i+35).map(x=>({fingerprint:x.fingerprint,note:x.content})),classified=await classifyIngredients(batch);let rows;if(classified.ok){aiModel=classified.model||aiModel;aiStatus='READY';const by=new Map((classified.results||[]).filter(x=>x?.fingerprint).map(x=>[x.fingerprint,x]));rows=batch.map(item=>{const r=by.get(item.fingerprint)||{},flowers=canonicalIngredients(r.flowers);return{fingerprint:item.fingerprint,content:item.note,flowers,needs_review:!!r.needs_review||!flowers.length,updated_at:new Date().toISOString()}})}else{aiStatus=classified.code||'LOCAL_FALLBACK';rows=batch.map(item=>{const flowers=localFlowers(item.note);return{fingerprint:item.fingerprint,content:item.note,flowers,needs_review:!flowers.length,updated_at:new Date().toISOString()}})}if(rows.length){await db('flower_cache',{on_conflict:'fingerprint'},'POST',rows);rows.forEach(r=>cache.set(r.fingerprint,r))}}const fpByKey=new Map(keyed.map(x=>[x.key,x.fingerprint])),groups=new Map(),reviewOrders=[];let analyzedOrders=0;for(const o of orders){const entry=cache.get(fpByKey.get(flowerKey(o.flower))),names=canonicalIngredients(entry?.flowers);if(entry)analyzedOrders++;if(!entry||entry.needs_review||!names.length)reviewOrders.push({id:o.id,customer:o.customer,flower:o.flower,date:o.order_date,time:cleanTime(o.order_time)});for(const name of names){const k=flowerKey(name),g=groups.get(k)||{name,orders:0,orderList:[]};if(!g.orderList.some(x=>x.id===o.id)){g.orders++;g.orderList.push({id:o.id,customer:o.customer,flower:o.flower,time:cleanTime(o.order_time),date:o.order_date})}groups.set(k,g)}}return{ok:true,status:reviewOrders.length?'needs_review':'ready',totalOrders:orders.length,analyzedOrders,reviewCount:reviewOrders.length,items:[...groups.values()].sort((a,b)=>b.orders-a.orders||a.name.localeCompare(b.name,'vi')),reviewOrders:reviewOrders.slice(0,100),aiModel,aiStatus,classifierVersion:'core6'}}

async function initialCore(user,token){const day=dateToday();if(user.role==='ADMIN')return {page:'dashboard',data:await fastDashboard({token,start:day,end:day}),at:Date.now()};if(user.role==='THO_OPS')return {page:'production',data:await fastProduction({token,date:day}),at:Date.now()};return {page:'orders',data:await fastOrders({token,start:day,end:day,page:1,pageSize:80}),at:Date.now()}}
async function loginAndBootstrapCore(payload){const result=await loginCore(payload);if(!result.ok)return result;return {...result,options:{shipping:['Shop book ship','Khách tự book','Ghé lấy'],statuses:['Chờ bó','Đã bó','Đã giao']},initial:await initialCore(result.user,result.token)}}
async function currentBootstrapCore(payload){const user=await requireUser(payload);return {ok:true,user:publicUser(user),initial:await initialCore(user,payload.token)}}

const mutationRoutes=new Set(['createOrder','updateOrder','saveShipFee','submitSettlement','saveShipAndSubmitSettlement','reviewSettlement','updateStatus']);
Deno.serve(async request=>{
  const origin=request.headers.get('origin')||'',allow=ALLOWED.includes(origin)?origin:ALLOWED[0];
  const cors={'Access-Control-Allow-Origin':allow,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'content-type, authorization, apikey','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};
  if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});
  if(request.method!=='POST')return new Response(JSON.stringify(fail('Method not allowed')),{status:405,headers:cors});
  const started=Date.now();
  try{
    const body=await request.text();if(new TextEncoder().encode(body).length>12*1024*1024)return new Response(JSON.stringify(fail('Dữ liệu gửi lên quá lớn.')),{status:413,headers:cors});
    const input=JSON.parse(body),name=clean(input?.name),payload=input?.payload&&typeof input.payload==='object'?input.payload:{};
    let result,status=200,legacyFallback=false;
    if(name==='loginAndBootstrap')result=await loginAndBootstrapCore(payload);
    else if(name==='getCurrentUserAndBootstrap')result=await currentBootstrapCore(payload);
    else if(name==='getProductionOrders')result=await fastProduction(payload);
    else if(name==='getOrders')result=await fastOrders(payload);
    else if(name==='getDashboardSummary')result=await fastDashboard(payload);
    else if(name==='getKpi')result=await fastKpi(payload);
    else if(name==='getFlowerInventory')result=await flowerInventory(payload);
    else if(name==='getOrder')result=await fastOrder(payload);
    else if(name==='getDebtReview')result=await fastDebt(payload);
    else if(name==='getFullPaidReport')result=await fullPaidReport(payload);
    else if(mutationRoutes.has(name)){
      const user=await requireUser(payload);
      const action=name==='saveShipAndSubmitSettlement'?'submitSettlement':name;
      const normalized=action==='reviewSettlement'?{...payload,settlementId:payload.settlementId||payload.requestId,requestId:payload.mutationRequestId||payload.requestId}:payload;
      result=await operationResult(action,normalized,user);
    }else{const up=await delegate(request,input);status=up.status;result=up.data;legacyFallback=true;}
    return new Response(JSON.stringify({...result,build:UI_BUILD,coreBuild:BUILD,_perf:{...(result?._perf||{}),serverMs:Date.now()-started,proxy:'core6',legacyFallback}}),{status,headers:cors});
  }catch(error){
    console.error('meehoasg core operation failed',error);
    const msg=String(error?.message||''),auth=/Phiên đăng nhập|Tài khoản đã bị khóa|Không có quyền/.test(msg);
    return new Response(JSON.stringify({...fail(auth?msg:'Chưa xác nhận được kết quả lưu. Giữ nguyên mã yêu cầu để thử lại.',auth?'AUTH_REQUIRED':'SERVER_ERROR'),build:UI_BUILD,coreBuild:BUILD}),{status:200,headers:cors});
  }
});
