const BUILD='2026.10.03-v365-consolidation-prep1';
const SUPABASE_URL=Deno.env.get('SUPABASE_URL');
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')||'';
const UPSTREAM=`${SUPABASE_URL}/functions/v1/meehoasg-api-v364`;
const ALLOWED=['https://ops.meehoasg.com','http://ops.meehoasg.com','https://meehoasg.com','http://meehoasg.com'];
function clean(v){return String(v??'').trim()}
function num(v){const n=Number(String(v??0).replace(/[^\d.-]/g,''));return Number.isFinite(n)?n:0}
function norm(v){return clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase()}
function saleKey(v){return norm(v).replace(/[^a-z0-9]/g,'')}
function cardQtyFromOrder(o){if(!o||!o.card)return 0;const q=Math.floor(num(o.cardQty));return Math.min(99,Math.max(1,q||1))}
async function db(table,query={},method='GET',body){const url=new URL(`${SUPABASE_URL}/rest/v1/${table}`);Object.entries(query).forEach(([k,v])=>{if(v!==undefined&&v!==null)url.searchParams.set(k,String(v))});const res=await fetch(url,{method,headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',Prefer:method==='GET'?'count=exact':'return=representation'},...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await res.text();if(!res.ok)throw new Error(`DB ${res.status}: ${text.slice(0,220)}`);return text?JSON.parse(text):[]}
async function userIdentityMap(){const users=await db('app_users',{select:'username,display_name,role,active',active:'eq.true'});const map=new Map();for(const u of users){map.set(saleKey(u.username),u);map.set(saleKey(u.display_name),u)}return map}
function canonicalSale(raw,map){const u=map.get(saleKey(raw));return u?{label:u.display_name,username:u.username}: {label:clean(raw)||'Chưa gán',username:''}}
async function canonicalizeDashboard(result){if(!result||!Array.isArray(result.salesDaily))return result;const map=await userIdentityMap(),merged=new Map();for(const x of result.salesDaily){const c=canonicalSale(x.sale,map),k=`${x.date}|${c.username||saleKey(c.label)}`;const y=merged.get(k)||{date:x.date,sale:c.label,username:c.username,orders:0,settledOrders:0,unsettledOrders:0,grossRevenue:0,settledRevenue:0,unsettledRevenue:0,revenue:0};['orders','settledOrders','unsettledOrders','grossRevenue','settledRevenue','unsettledRevenue'].forEach(f=>y[f]+=num(x[f]));y.revenue=y.settledRevenue;merged.set(k,y)}result.salesDaily=[...merged.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))||(b.grossRevenue-a.grossRevenue)||String(a.sale).localeCompare(String(b.sale),'vi'));result.saleIdentityRule='APP_USERS_CANONICAL';return result}
async function canonicalizeKpi(result){if(!result||!Array.isArray(result.items))return result;const map=await userIdentityMap(),merged=new Map();for(const x of result.items){const c=canonicalSale(x.username||x.sale,map),k=c.username||saleKey(c.label),y=merged.get(k)||{sale:c.label,username:c.username,revenue:0,orders:0,bigOrders:0,operationsScore:100};y.revenue+=num(x.revenue);y.orders+=num(x.orders);y.bigOrders+=num(x.bigOrders);y.operationsScore=Math.min(y.operationsScore,num(x.operationsScore||100));merged.set(k,y)}const holiday=!!result.holiday,target=holiday?50000000:38000000,bigTarget=holiday?20:16;result.items=[...merged.values()].map(x=>{x.level1=holiday?x.revenue>=target:x.revenue>target;x.bigTarget=bigTarget;x.level2=x.level1&&x.bigOrders>=bigTarget&&x.operationsScore>80;x.rate=x.level2?.10:.08;x.commission=x.revenue*x.rate;x.bonus=x.level1?300000:0;return x});result.saleIdentityRule='APP_USERS_CANONICAL';return result}
async function orderCardRows(ids){ids=[...new Set((ids||[]).filter(Boolean))];if(!ids.length)return[];const out=[];for(let i=0;i<ids.length;i+=40){const chunk=ids.slice(i,i+40);out.push(...await db('orders',{select:'id,card,card_qty,banner,charm_fee,paper_fee,flower_total,vat,shipping,ship_fee,settled,payment',id:'in.('+chunk.map(x=>'"'+String(x).replaceAll('"','')+'"').join(',')+')'}))}return out}
function adjustOrder(o,row){if(!o||!row)return o;const qty=row.card?Math.max(1,Math.floor(num(row.card_qty)||1)):0;const previous=o.card?1:0;const delta=(qty-previous)*10000;o.cardQty=qty;o.cardFee=qty*10000;o.accessoryTotal=Math.max(0,num(o.accessoryTotal)+delta);if('totalDue'in o)o.totalDue=Math.max(0,num(o.totalDue)+delta);if('debt'in o&&!o.settled)o.debt=Math.max(0,num(o.debt)+delta);return o}
async function enrichList(items){items=Array.isArray(items)?items:[];const rows=await orderCardRows(items.map(x=>x&&x.id));const map=new Map(rows.map(r=>[r.id,r]));items.forEach(x=>adjustOrder(x,map.get(x&&x.id)));return items}
async function enrichResult(name,payload,result){if(!result||!result.ok)return result;if(name==='createOrder'||name==='updateOrder'){const id=result.orderId||result.order?.id,q=cardQtyFromOrder(payload?.order||{});if(id)await db('orders',{id:`eq.${id}`},'PATCH',{card_qty:q});if(result.order&&id){const rows=await orderCardRows([id]);adjustOrder(result.order,rows[0])}return result}if(name==='saveShipAndSubmitSettlement'&&result.orderId&&result.requestId){const rows=await orderCardRows([result.orderId]),r=rows[0];if(r){const accessory=(r.card?Math.max(1,num(r.card_qty))*10000:0)+(r.banner?35000:0)+num(r.charm_fee)+num(r.paper_fee),ship=norm(r.shipping).includes('shop')?num(r.ship_fee):0,required=num(r.flower_total)+accessory+num(r.vat)+ship;await db('settlement_requests',{id:`eq.${result.requestId}`},'PATCH',{accessory_total:accessory,required_amount:required});result.accessoryTotal=accessory;result.requiredAmount=required}return result}if(name==='getOrders'){await enrichList(result.items);return result}if(name==='getProductionOrders'){await enrichList(result.orders);return result}if(name==='getDebtReview'){await enrichList(result.items);return result}if(name==='getOrder'&&result.order){const rows=await orderCardRows([result.order.id]);adjustOrder(result.order,rows[0]);return result}if(name==='getSettlementQueue'&&Array.isArray(result.items)){await enrichList(result.items.map(x=>x&&x.order).filter(Boolean));return result}if(name==='getDashboardSummary'){await enrichList(result.attention||[]);if(result.attentionGroups){await enrichList(result.attentionGroups.nearUnpacked||[]);await enrichList(result.attentionGroups.packedOverdue||[])}const start=clean(payload.start),end=clean(payload.end)||start;if(start&&result.summary){const rows=await db('orders',{select:'card,card_qty,settled',and:`(order_date.gte.${start},order_date.lte.${end})`});result.summary.debt=num(result.summary.debt)+rows.reduce((s,r)=>s+(!r.settled&&r.card?Math.max(0,num(r.card_qty)-1)*10000:0),0)}return canonicalizeDashboard(result)}if(name==='getKpi')return canonicalizeKpi(result);if((name==='loginAndBootstrap'||name==='getCurrentUserAndBootstrap')&&result.initial&&result.initial.data){const p=result.initial.page,d=result.initial.data;if(p==='orders')await enrichList(d.items);else if(p==='production')await enrichList(d.orders);else if(p==='dashboard'){await enrichList(d.attention||[]);if(d.attentionGroups){await enrichList(d.attentionGroups.nearUnpacked||[]);await enrichList(d.attentionGroups.packedOverdue||[])}await canonicalizeDashboard(d)}return result}return result}
async function upstream(req,input){const h={'Content-Type':'application/json'},auth=req.headers.get('authorization'),api=req.headers.get('apikey');if(auth)h.Authorization=auth;if(api)h.apikey=api;else if(ANON_KEY)h.apikey=ANON_KEY;const r=await fetch(UPSTREAM,{method:'POST',headers:h,body:JSON.stringify(input)}),t=await r.text();let data;try{data=t?JSON.parse(t):{}}catch{data={ok:false,message:'Phản hồi máy chủ không hợp lệ.'}}return {status:r.status,data}}
async function repairBootstrapOrders(req,name,payload,up){if(!['loginAndBootstrap','getCurrentUserAndBootstrap'].includes(name)||up?.data?.initial?.page!=='orders')return up;const token=name==='loginAndBootstrap'?clean(up.data.token):clean(payload.token);if(!token)return up;const day=clean(payload.today)||clean(up.data.initial.data?.range?.start)||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const fresh=await upstream(req,{name:'getOrders',payload:{token,start:day,end:day,page:1,pageSize:80}});if(fresh.data?.ok)up.data.initial={...up.data.initial,data:fresh.data,at:Date.now()};return up}
Deno.serve(async req=>{const origin=req.headers.get('origin')||'',allow=ALLOWED.includes(origin)?origin:ALLOWED[0],cors={'Access-Control-Allow-Origin':allow,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'content-type, authorization, apikey','Content-Type':'application/json; charset=utf-8','Vary':'Origin'};if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({ok:false,message:'Method not allowed'}),{status:405,headers:cors});try{const input=await req.json(),name=clean(input?.name),payload=input?.payload&&typeof input.payload==='object'?input.payload:{},started=Date.now();let up=await upstream(req,input);up=await repairBootstrapOrders(req,name,payload,up);const data=await enrichResult(name,payload,up.data);return new Response(JSON.stringify({...data,proxyBuild:BUILD,_v365ms:Date.now()-started}),{status:up.status,headers:cors})}catch(e){console.error(e);return new Response(JSON.stringify({ok:false,message:'Máy chủ gặp lỗi. Vui lòng thử lại.',code:'SERVER_ERROR',proxyBuild:BUILD}),{status:200,headers:cors})}});
