const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const assets = path.join(root, 'assets');

const cssFiles = [
  'meehoa-v3.css',
  'meehoa-v3-fix.css',
  'meehoa-v3-hotfix.css',
  'meehoa-v34.css',
  'meehoa-v35.css',
  'meehoa-prod-fix.css',
  'meehoa-v362.css',
  'meehoa-v364.css',
  'meehoa-scroll-contract.css',
  'meehoa-v365.css'
];

const jsFiles = [
  'meehoa-v3.js',
  'meehoa-v34.js',
  'meehoa-v35.js',
  'meehoa-v361.js',
  'meehoa-v362.js',
  'meehoa-v363.js',
  'meehoa-v364.js',
  'meehoa-v365.js'
];

function bundle(files, kind) {
  const chunks = files.map(file => {
    const full = path.join(assets, file);
    if (!fs.existsSync(full)) throw new Error(`Missing ${file}`);
    const src = fs.readFileSync(full, 'utf8').trim();
    return `/* ===== ${file} ===== */\n${src}\n`;
  });
  const banner = `/* MEEHOA CONSOLIDATED ${kind.toUpperCase()} CORE\n * Generated by scripts/build-runtime.cjs\n * Source order is intentional; later compatibility rules win exactly as before.\n */\n`;
  return banner + chunks.join('\n');
}

const css = bundle(cssFiles, 'css');
const js = bundle(jsFiles, 'js');
fs.writeFileSync(path.join(assets, 'meehoa-core.css'), css);
fs.writeFileSync(path.join(assets, 'meehoa-core.js'), js);

const sourceCssBytes = cssFiles.reduce((n, f) => n + fs.statSync(path.join(assets, f)).size, 0);
const sourceJsBytes = jsFiles.reduce((n, f) => n + fs.statSync(path.join(assets, f)).size, 0);
const metrics = {
  generatedAt: new Date().toISOString(),
  cssFiles,
  jsFiles,
  sourceRequestsBefore: cssFiles.length + jsFiles.length,
  runtimeRequestsAfter: 2,
  sourceCssBytes,
  sourceJsBytes,
  coreCssBytes: Buffer.byteLength(css),
  coreJsBytes: Buffer.byteLength(js)
};
fs.writeFileSync(path.join(root, 'runtime-metrics.json'), JSON.stringify(metrics, null, 2) + '\n');
console.log(JSON.stringify(metrics, null, 2));
