const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const assets = path.join(root, 'assets');

/*
 * Canonical runtime contract:
 * - one owner per feature domain;
 * - no *fix*, *hotfix* or compatibility-only source may enter production core;
 * - later modules may depend on earlier base markup, but must not re-implement another domain.
 */
const cssFiles = [
  'meehoa-v3.css',
  'meehoa-v34.css',
  'meehoa-v35.css',
  'meehoa-v361.css',
  'meehoa-v362.css',
  'meehoa-v364.css',
  'meehoa-v365.css'
];

const jsFiles = [
  'meehoa-v3.js',
  'meehoa-v34.js',
  'meehoa-v35.js',
  'meehoa-v361.js',
  'meehoa-v362.js',
  'meehoa-v364.js',
  'meehoa-v366.js',
  'meehoa-order-actions.js'
];

const forbiddenRuntimeNames = /(?:fix|hotfix|runtime-fix|ops-hotfix|scroll-contract)/i;
for (const file of [...cssFiles, ...jsFiles]) {
  if (forbiddenRuntimeNames.test(file)) throw new Error(`Non-canonical runtime layer is forbidden: ${file}`);
}

const ownership = JSON.parse(fs.readFileSync(path.join(root, 'runtime-ownership.json'), 'utf8'));
const ownedFiles = new Set(Object.values(ownership).flatMap(x => x.files || []));
for (const file of [...cssFiles, ...jsFiles]) {
  if (!ownedFiles.has(file)) throw new Error(`Runtime source has no declared owner: ${file}`);
}

const sharedObserverPrelude = `/* MEEHOA shared MutationObserver multiplexer */
(function(){
  if(typeof window==='undefined'||typeof window.MutationObserver!=='function'||window.__MEE_SHARED_MUTATION_OBSERVER__)return;
  var Native=window.MutationObserver, virtuals=new Set(), observed=new Map();
  var nativeObserver=new Native(function(records){
    virtuals.forEach(function(v){
      if(!v.active||!v.targets.length)return;
      var mine=records.filter(function(r){return v.targets.some(function(t){return r.target===t.target||(t.options.subtree&&t.target&&t.target.contains&&t.target.contains(r.target))})});
      if(mine.length){try{v.callback(mine,v)}catch(err){setTimeout(function(){throw err},0)}}
    });
  });
  function mergeOptions(a,b){a=a||{};b=b||{};return {childList:!!(a.childList||b.childList),attributes:!!(a.attributes||b.attributes),characterData:!!(a.characterData||b.characterData),subtree:!!(a.subtree||b.subtree)} }
  function SharedMutationObserver(callback){this.callback=callback;this.targets=[];this.active=true;virtuals.add(this)}
  SharedMutationObserver.prototype.observe=function(target,options){if(!target)return;this.active=true;virtuals.add(this);this.targets.push({target:target,options:options||{}});var merged=mergeOptions(observed.get(target),options);observed.set(target,merged);nativeObserver.observe(target,merged)};
  SharedMutationObserver.prototype.disconnect=function(){this.targets=[];this.active=false;virtuals.delete(this)};
  SharedMutationObserver.prototype.takeRecords=function(){return[]};
  window.MutationObserver=SharedMutationObserver;
  window.__MEE_SHARED_MUTATION_OBSERVER__=true;
})();
`;

function sourceChunks(files) {
  return files.map(file => {
    const full = path.join(assets, file);
    if (!fs.existsSync(full)) throw new Error(`Missing ${file}`);
    const src = fs.readFileSync(full, 'utf8').trim();
    return { file, src, block: `/* ===== ${file} ===== */\n${src}\n` };
  });
}

const cssChunks = sourceChunks(cssFiles);
const jsChunks = sourceChunks(jsFiles);
const cssBanner = `/* MEEHOA CANONICAL CSS CORE\n * Generated by scripts/build-runtime.cjs\n * Feature ownership is declared in runtime-ownership.json.\n */\n`;
const jsBanner = `/* MEEHOA CANONICAL JS CORE\n * Generated by scripts/build-runtime.cjs\n * Feature ownership is declared in runtime-ownership.json; one native MutationObserver is shared.\n */\n`;
const css = cssBanner + cssChunks.map(x => x.block).join('\n');
const js = jsBanner + sharedObserverPrelude + jsChunks.map(x => x.block).join('\n');
fs.writeFileSync(path.join(assets, 'meehoa-core.css'), css);
fs.writeFileSync(path.join(assets, 'meehoa-core.js'), js);

const sourceCssBytes = cssFiles.reduce((n, f) => n + fs.statSync(path.join(assets, f)).size, 0);
const sourceJsBytes = jsFiles.reduce((n, f) => n + fs.statSync(path.join(assets, f)).size, 0);
const sourceMutationObservers = jsChunks.reduce((n, x) => n + (x.src.match(/new\s+MutationObserver\s*\(/g) || []).length, 0);
const metrics = {
  schemaVersion: 2,
  architecture: 'single-owner-modules',
  cssFiles,
  jsFiles,
  sourceRequestsBefore: cssFiles.length + jsFiles.length,
  runtimeRequestsAfter: 2,
  sourceCssBytes,
  sourceJsBytes,
  coreCssBytes: Buffer.byteLength(css),
  coreJsBytes: Buffer.byteLength(js),
  sourceMutationObservers,
  nativeMutationObserversAfter: sourceMutationObservers ? 1 : 0
};
fs.writeFileSync(path.join(root, 'runtime-metrics.json'), JSON.stringify(metrics, null, 2) + '\n');
console.log(JSON.stringify(metrics, null, 2));
